export const navArray = [
  {
    id: 1,
    title: 'Inicio',
    icon: 'faHouse',
    url: '/home',
  },
  {
    id: 2,
    title: 'Nuestras mejores ofertas',
    icon: 'faGlobe',
    url: '/travel/betterOffers',
  },
  {
    id: 3,
    title: 'Promociones vigentes',
    icon: 'faTags',
    url: '/travel/currentOffers',
  },
  {
    id: 4,
    title: 'Destinos',
    icon: 'faPlane',
    destinos: [
      {
        id: 4,
        title: 'Europa',
        img: '1-europa.png',
        url: '/travel/europa',
      },
      {
        id: 5,
        title: 'Medio Oriente',
        img: '2-medioOriente.png',
        url: '/travel/medioOriente',
      },
      {
        id: 6,
        title: 'Canadá', 
        img: '3-Canada.png',
        url: '/travel/canada',
      },
      {
        id: 7,
        title: 'Asia',
        img: '4-asia.png', 
        url: '/travel/asia',
      },
      {
        id: 8,
        title: 'África',
        img: '5-africa.png',   
        url: '/travel/africa',
      },
      {
        id: 10,
        title: 'Pacífico',
        url: '/travel/pacific',
        img: '6-pacifico.png', 
      },
      {
        id: 11,
        title: 'Sudamérica',
        img: '9-sudamerica.png', 
        url: '/travel/southAmerica',
      },
      {
        id: 12,
        title: 'Estados Unidos',
        url: '/travel/eua',
        img: '8-usa.png', 
      },
      {
        id: 13,
        title: 'Centroamérica',
        img: '7-sudamerica.png', 
        url: '/travel/centerAmerica',
      },
      {
        id: 14,
        title: 'Cuba y el Caribe',
        img: '10-caribe.png', 
        url: '/travel/cubaCaribean',
      },
      {
        id: 15,
        title: 'Nacionales',
        img: '11-Mexico.png', 
        url: '/travel/nacional',
      },
      {
        id: 16,
        title: 'Eventos especiales',
        img: '12-eventosEspeciales.png', 
        url: '/travel/specialesEvents',
      },
      {
        id: 17,
        title: 'Cruceros',
        img: '13-Cruceros.png', 
        url: '/travel/cruises',
      },
    ],
  },
  // {
  //   id: 19,
  //   title: 'Explorar',
  //   icon: 'faGlobe',
  //   url: '/explorar',
  // },
  {
    id: 17,
    title: 'Contacto',
    icon: 'faPhone',
    url: '/contact',
  },
];
